Repository eslint-types/eslint-define-config, pull requests merged in 2023-10, with the labels that each got.

#239 Fix rule generation
  scripts/generate-rule-files/diffs/rules/typescript-eslint/array-type.d.ts.diff
  scripts/generate-rule-files/diffs/rules/typescript-eslint/ban-ts-comment.d.ts.diff
  scripts/generate-rule-files/diffs/rules/typescript-eslint/explicit-member-accessibility.d.ts.diff
  scripts/generate-rule-files/diffs/rules/typescript-eslint/lines-between-class-members.d.ts.diff
  scripts/generate-rule-files/diffs/rules/typescript-eslint/parameter-properties.d.ts.diff
  scripts/generate-rule-files/diffs/rules/vitest/valid-title.d.ts.diff
  scripts/generate-rule-files/src/json-schema-to-ts.ts
  scripts/generate-rule-files/src/rule-file.ts
  src/rules/testing-library/await-async-query.d.ts
  src/rules/testing-library/await-fire-event.d.ts
  src/rules/testing-library/index.d.ts
  src/rules/testing-library/no-await-sync-query.d.ts
  src/rules/testing-library/no-render-in-setup.d.ts
  src/rules/testing-library/no-wait-for-empty-callback.d.ts
  src/rules/testing-library/prefer-wait-for.d.ts
  src/rules/typescript-eslint/array-type.d.ts
  src/rules/typescript-eslint/ban-ts-comment.d.ts
  src/rules/typescript-eslint/ban-types.d.ts
  src/rules/typescript-eslint/explicit-member-accessibility.d.ts
  src/rules/typescript-eslint/explicit-module-boundary-types.d.ts
  src/rules/typescript-eslint/index.d.ts
  src/rules/typescript-eslint/member-delimiter-style.d.ts
  src/rules/typescript-eslint/member-ordering.d.ts
  src/rules/typescript-eslint/no-duplicate-imports.d.ts
  src/rules/typescript-eslint/no-implicit-any-catch.d.ts
  src/rules/typescript-eslint/no-misused-promises.d.ts
  src/rules/typescript-eslint/no-parameter-properties.d.ts
  src/rules/typescript-eslint/no-type-alias.d.ts
  src/rules/typescript-eslint/no-unnecessary-type-assertion.d.ts
  src/rules/typescript-eslint/parameter-properties.d.ts
  src/rules/typescript-eslint/prefer-readonly.d.ts
  src/rules/typescript-eslint/require-array-sort-compare.d.ts
  src/rules/typescript-eslint/restrict-template-expressions.d.ts
  src/rules/typescript-eslint/sort-type-constituents.d.ts
  src/rules/typescript-eslint/sort-type-union-intersection-members.d.ts
  src/rules/typescript-eslint/type-annotation-spacing.d.ts
  src/rules/typescript-eslint/typedef.d.ts
  src/rules/vitest/valid-title.d.ts
Labels: bug

#243 Fix missing build files in package.json
  package.json
Labels: bug

#238 Support augmented global properties
  README.md
  src/config/extends/index.d.ts
  src/config/index.d.ts
  src/config/overrides.d.ts
  src/config/plugin.d.ts
  src/config/settings/index.d.ts
  src/flat-config/index.d.ts
  src/parser-options.d.ts
  src/rules/index.d.ts
Labels: enhancement

#251 Fix single schema generation
  scripts/generate-eslint-dts.ts
  src/rules/eslint/array-element-newline.d.ts
  src/rules/eslint/arrow-body-style.d.ts
  src/rules/eslint/comma-dangle.d.ts
  src/rules/eslint/consistent-this.d.ts
  src/rules/eslint/curly.d.ts
  src/rules/eslint/eqeqeq.d.ts
  src/rules/eslint/func-call-spacing.d.ts
  src/rules/eslint/func-name-matching.d.ts
  src/rules/eslint/func-names.d.ts
  src/rules/eslint/id-blacklist.d.ts
  src/rules/eslint/id-denylist.d.ts
  src/rules/eslint/init-declarations.d.ts
  src/rules/eslint/logical-assignment-operators.d.ts
  src/rules/eslint/multiline-comment-style.d.ts
  src/rules/eslint/no-extra-parens.d.ts
  src/rules/eslint/no-restricted-globals.d.ts
  src/rules/eslint/no-restricted-imports.d.ts
  src/rules/eslint/no-restricted-modules.d.ts
  src/rules/eslint/no-restricted-properties.d.ts
  src/rules/eslint/no-restricted-syntax.d.ts
  src/rules/eslint/object-shorthand.d.ts
  src/rules/eslint/padding-line-between-statements.d.ts
  src/rules/eslint/quote-props.d.ts
  src/rules/eslint/semi.d.ts
Labels: bug

#253 Self use eslint-types
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
Labels: dependencies
